name: cardi_care
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  firebase_core: ^2.31.0
  flutter_riverpod: ^2.5.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  riverpod: ^2.5.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  zoom_tap_animation: ^1.1.0
  two_dimensional_scrollables: ^0.3.1
  cloud_firestore: ^4.17.5
  freezed: ^2.5.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
