// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzncqrbwHii044PGQ1ra4TJ0v91y_f8Nc',
    appId: '1:187909067652:web:a479c22a4a0895dee4c3d1',
    messagingSenderId: '187909067652',
    projectId: 'teka-teki-silang-71ac4',
    authDomain: 'teka-teki-silang-71ac4.firebaseapp.com',
    storageBucket: 'teka-teki-silang-71ac4.appspot.com',
    measurementId: 'G-JYZEYFE9FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Yoa2QnMzXGuqAQRpOv9ecRIJDmkVklU',
    appId: '1:187909067652:android:7fdf33dfe8878ab8e4c3d1',
    messagingSenderId: '187909067652',
    projectId: 'teka-teki-silang-71ac4',
    storageBucket: 'teka-teki-silang-71ac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nlK0t7GWMLmITyHeBsJGIbVyvhZ4oEE',
    appId: '1:187909067652:ios:094e8e5a693787c3e4c3d1',
    messagingSenderId: '187909067652',
    projectId: 'teka-teki-silang-71ac4',
    storageBucket: 'teka-teki-silang-71ac4.appspot.com',
    iosBundleId: 'com.example.cardiCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9nlK0t7GWMLmITyHeBsJGIbVyvhZ4oEE',
    appId: '1:187909067652:ios:094e8e5a693787c3e4c3d1',
    messagingSenderId: '187909067652',
    projectId: 'teka-teki-silang-71ac4',
    storageBucket: 'teka-teki-silang-71ac4.appspot.com',
    iosBundleId: 'com.example.cardiCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzncqrbwHii044PGQ1ra4TJ0v91y_f8Nc',
    appId: '1:187909067652:web:091dd1a05b15ddf1e4c3d1',
    messagingSenderId: '187909067652',
    projectId: 'teka-teki-silang-71ac4',
    authDomain: 'teka-teki-silang-71ac4.firebaseapp.com',
    storageBucket: 'teka-teki-silang-71ac4.appspot.com',
    measurementId: 'G-7PSV91P93K',
  );

}